### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by hentai-chan** [karnkaul/djson#1]
There are a couple of issues I encountered when I used this library:

### 1. Breaks on empty lists

```json
{
    "test": []
}
```

**Error Message**: `[djson] Error: Expected token: `}`, obtained: `]` [l: 2 | c: 13]`

```json
{
    "test": [""]
}
```

**Error Message**: `Assertion failed: quote(sub.peek()), file ..\..\..\libs\djson\src\detail\lexer.cpp, line 122`

### 2. Breaks on nested Quotes

```json
{
    "test": "That's splendid!"
}
```

**Error Message**: `[djson] Error: Expected token: `}`, obtained: `]` [l: 2 | c: 18]`

The reverse is also true (though not confirming with JSON specs):

```json
{
    "test": 'That"s splendid!'
}
```

**Comment by karnkaul** [comment]
Thanks for the detailed report, @hentai-chan! I'll be submitting a patch soon; if you could test that branch on some sample code, that would be amazing.

**Comment by karnkaul** [comment]
Here's the PR: https://github.com/karnkaul/djson/pull/2

On your end just run `git fetch && git checkout issue-1-fix` to test.

**Comment by hentai-chan** [comment]
@karnkaul looking good, I tested all the edge cases mentioned in this PR and have no complaints so far
